### ISSUE TITLE
Crash on Login (Android 8)

### ISSUE THREAD

**Issue by leewp14** [pydio/cells-android-client#33]
On a functional Cells setup, using two Android clients as well as a desktop client: 
1. Desktop Client - OK
2. Android Client (Android 11) - OK
3. Android Client (Android 8.1.0) - Crash after trying to login

Android client on both Android devices will show Invalid Certificate error although the certificate is valid when opening in browser. Android 11 successfully logged in after press "OK, I understand the risks". But Android 8 crash shortly after pressing it. Below is the crash log: 

`01-30 02:42:56.663  3073  3073 E AndroidRuntime: FATAL EXCEPTION: main
01-30 02:42:56.663  3073  3073 E AndroidRuntime: Process: com.pydio.android.Client, PID: 3073
01-30 02:42:56.663  3073  3073 E AndroidRuntime: java.lang.StackOverflowError: stack size 8MB
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at java.lang.StringBuffer.append(StringBuffer.java:381)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at java.io.StringWriter.write(StringWriter.java:77)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.stream.JsonWriter.string(JsonWriter.java:617)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.stream.JsonWriter.writeDeferredName(JsonWriter.java:402)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.stream.JsonWriter.value(JsonWriter.java:417)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$15.write(TypeAdapters.java:425)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapters$15.write(TypeAdapters.java:409)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.663  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.800  3073  3085 I zygote64: Background concurrent copying GC freed 90556(7MB) AllocSpace objects, 18(3MB) LOS objects, 50% free, 29MB/59MB, paused 129us total 115.485ms
01-30 02:42:56.848  3073  3073 I chatty  : uid=10107(com.pydio.android.Client) identical 862 lines
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:207)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.write(MapTypeAdapterFactory.java:144)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:70)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:196)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:366)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:825)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:795)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:742)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.google.gson.Gson.toJson(Gson.java:719)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.pydio.cells.transport.ServerURLImpl.toJson(ServerURLImpl.java:167)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.pydio.android.cells.ui.auth.ServerUrlFragment$onCreateView$2.invoke(ServerUrlFragment.kt:48)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.pydio.android.cells.ui.auth.ServerUrlFragment$onCreateView$2.invoke(ServerUrlFragment.kt:45)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.pydio.android.cells.ui.auth.ServerUrlFragment.onCreateView$lambda$1(ServerUrlFragment.kt:45)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.pydio.android.cells.ui.auth.ServerUrlFragment.$r8$lambda$H4nLXtNEVtEdHOzBExu0AIi6AJ0(Unknown Source:0)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.pydio.android.cells.ui.auth.ServerUrlFragment$$ExternalSyntheticLambda1.onChanged(Unknown Source:2)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at androidx.lifecycle.MutableLiveData.setValue(MutableLiveData.java:50)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.pydio.android.cells.ui.auth.ServerUrlViewModel$pingAddress$1.invokeSuspend(ServerUrlViewModel.kt:88)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:790)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
01-30 02:42:56.848  3073  3073 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
01-30 02:42:57.014   982  7733 W ActivityManager:   Force finishing activity com.pydio.android.Client/com.pydio.android.cells.AuthActivity
01-30 02:42:57.022   982  1216 I ActivityManager: Showing crash dialog for package com.pydio.android.Client u0
`

**Comment by bsinou** [comment]
Hi, 

Thanks for reporting. Could you please precise / confirm:

- which version of the android app you use
- the android 8.1 device is API Level 27 right?  (see https://source.android.com/docs/setup/about/build-numbers -> this should be working, we support API Level 21)
- to reproduce, you simply:
   - open the app
   - enter a new URL
   - perform the login on your server (OAuth flow via the web UI)
   - the app crashes when you are back in it after auth, right ?
